### ISSUE TITLE
The toolkit - Let's make sure to pick the tools we like to work with and that can help us achieve great things!

### ISSUE THREAD

**Issue by daviddias** [ipfs/ipfs-gui#13]
One of the points brought up during the kick off call is _what tools and services to use_ to collaborate in this project.

Historically, we have used at Protocol Labs a waterfall style where:

- One of us brain dumps the idea for the design (in a very comprehensive way) - Github issue
- Wireframe gets created and iterations start to happen - Invision or Zeplin
- Design and Content gets created - Invision or Zeplin
- Code gets written

This process is not set in stone and I would love to have something that after the first launch, we can open to the community and make it easier for everyone to contribute with changes (git/github style).

What is everyone's experience? What worked really well in the past and what didn't?

**Comment by ericronne** [comment]
the nascent [design process](https://app.gitbook.com/@protocol-labs/s/handbook/design/toolbox) outlined by @jessicaschilling will inform this

**Comment by jessicaschilling** [comment]
This is an interesting conversation ... one of the intentions of the [toolbox](https://app.gitbook.com/@protocol-labs/s/handbook/design/toolbox) was to give folks some pointers for how to get sticky design-related questions under control without being too prescriptive in the order in which we wanted to do things -- both in terms of avoiding some of the waterfall thinking referred to above, but also because different teams will be inclined to swarm/solve on stuff in very different manners just based on diversity of team skills, existing team norms, how distributed everyone is (are key players close enough in time zones to have ongoing realtime discussions or is everything going to be totally async), etc etc etc.

That said, we're already starting to see some methodologies for the order in which we do stuff emerging. Maybe this is something we keep a pulse on for a little bit and re-address?

**Comment by jessicaschilling** [comment]
Closing this issue, as we're discussing in other venues.
