### ISSUE TITLE
Design: Share files via IPFS

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#34]
How do we make sharing files via IPFS feel great? It's the first thing I tried to do with IPFS, and I think it's something we should invest some time into making really good.

This is closely related to "Add files" #35 and "File Browsing" #9, as you might want to add and share a new file, or browse for a file you added to IPFS previously and (re)share that.

Related issue on companion: https://github.com/ipfs-shipyard/ipfs-companion/issues/342

The current state of things is described here: https://github.com/ipfs-shipyard/pm-ipfs-gui/blob/master/research/README.md#sharing-files

**Comment by olizilla** [comment]
Related issue on companion: https://github.com/ipfs-shipyard/ipfs-companion/issues/342

**Comment by olizilla** [comment]
Sharing right now consists of choices like "Should I share the public gateway http link, or should I share the `/ipfs/Qmhash` path". The apps all do variations on that. I think we can do better. 

We'll always offer the user a url they can copy/paste (much like the copy to clipboard share action on android), but we could offer a more polished sharing experience, where we create an html page that includes a down link to for the file the user wants to share, along with the filename, it's size and it's CID. 

The page could provide a concise explanation of IPFS, and a link to more info, along with an call to action to install IPFS so that they too can share files with peers without needing intermediaries. GET ON BOARD THE PEER-TRAIN! 🚋 🚋 🚋.

Offering an explicit "Share this file" action would connect up nicely with the idea of being able to indicate to group of friendly peers that a specific CID is gonna get linked to, and they should take note and pin that hash to increase it's availability, discussed in #36 "pinning buddy system".

**Comment by olizilla** [comment]
At the simpler end of things, we need to talk about the [4 flavours of IPFS address](https://ipfs.io/ipfs/QmP2yCrvuL89kgCxtt5vXfPMt89PtidxQ8yKTr86gtYZd4) and how we express that to users. 

I'd suggest that right now, for the purpose of interop and progressive enhancement, we should always offer the user the http, gateway url flavour when offering shareable links to files. We can show the NURI style CID as info about the file that they can choose to copy and paste, but anything that is labelled as "Share this file" should be giving the user a http link. 

Companion can grab that and redirect it to a local IPFS repo,  (See https://github.com/ipfs-shipyard/pm-ipfs-gui/issues/37) so existing users are fine, and we don't exclude users we haven't met yet.

**Comment by olizilla** [comment]
https://github.com/ipfs-shipyard/ipfs-companion/issues/423 - Display IPFS addresses instead of opening uploaded file

**Comment by akrych** [comment]
> When the recipient clicks the link (probably a http, central gateway flavoured link for now) they see the lovely download page customised just for them. It gives them a moment to consider if they want to download it at all, and invites them to install IPFS to download it directly from their peers if they want to join the fun, or just grab the file and get on with their lives, but now with a new idea in their head that there might just be a better way.

Love the idea :) 👍 What should we have on this page? File preview, CID, button to download, encouraged to install IPFS, download button, short explanation of IPFS?

**Comment by lidel** [comment]
Yes! :+1:   My thoughts on what the page should have:

- visible IPFS logo  and branding
- name and size of shared file/directory
  - eg: `persian-room-guardian.jpg` `~117KiB`
  - the most important element, should visually pop to instantly see what was shared
  - it could be accompanied by a file (or directory) icon 
    (we plan to support sharing entire directories)
- "shareable" link to the file at our public gateway that user can send to a friend on IM or via email
  - eg. `https://ipfs.io/ipfs/QmRAJM5ByzuKKpzKKisGDwBPHzYqMvVrYC2PcVhkMnP3gd/persian-room-guardian.jpg`
- a short disclaimer informing uploader/receiver that public gateway does not guarantee availability of content after X hours 
   - main reason: we need to be explicitly honest about gateway not keeping files forever, so there is no negative UX when not pinned content disappears from public gateway next week
   - secondary reason here is nudging users to install IPFS and pin content they care about to stay available for longer
- a longer section with additional info
  [this may be  optional, displayed only if user has no IPFS (eg. no `window.ipfs` is found)]
  - short explanation of IPFS
  - a call to action to install IPFS so that user can share and pin files with peers without needing any intermediaries.
  - I'd like to include @Mr0grog  here, as he may have a very good intuition on what exact text should be used to convey all of this info in a short and digestible form.

**Comment by olizilla** [comment]
Using https://wetransfer.com/ to share some files with <20 people via email or shareable link, looks like this (such much advert)

## Sender

![screen shot 2018-03-22 at 14 51 29](https://user-images.githubusercontent.com/58871/37779243-dd3831cc-2de3-11e8-8ad9-39cf84cd151c.png)


### Send via email

![screen shot 2018-03-22 at 14 51 41](https://user-images.githubusercontent.com/58871/37779272-f0e703a6-2de3-11e8-95cf-739018684d83.png)

### Send via link

![screen shot 2018-03-22 at 15 19 20](https://user-images.githubusercontent.com/58871/37779530-84c49c5a-2de4-11e8-9449-6dd7196de779.png)


## Recipient

<img width="996" alt="screen shot 2018-03-22 at 14 52 22" src="https://user-images.githubusercontent.com/58871/37779291-fbea2c2e-2de3-11e8-861b-9d4514430622.png">

<img width="996" alt="screen shot 2018-03-22 at 14 52 30" src="https://user-images.githubusercontent.com/58871/37779298-0310a866-2de4-11e8-8207-619fada132ee.png">

**Comment by olizilla** [comment]
**Drag n drop a file to share it**

## Slack

![screen shot 2018-03-22 at 16 18 13](https://user-images.githubusercontent.com/58871/37783523-9bfcfb0c-2ded-11e8-846f-ddc54e5bac78.png)

## web.whatsapp.com

![screen shot 2018-03-22 at 16 19 14](https://user-images.githubusercontent.com/58871/37783535-a488b4a0-2ded-11e8-8158-aae84b04d096.png)

**Comment by alanshaw** [comment]
I'm possibly getting ahead of myself here but, we should "standardise" the format of the shared "file" so that it's easy to extract/link to the data from the download page or without having to view the download page at all.

```
QmHash/index.html <--- the download page with all the info
QmHash/.share-v0 <--- indicate this is a shared file/folder with a download page
QmHash/data <--- always a **folder** with the shared file enclosed
```

`index.html` - the download page which can link directly to the hash of the file (if a single file) or to the hash of /data if multiple

`.share-v0` - is just a placeholder file so that if we ever are given a hash and programmatically want to get hold of the data, we can inspect the directory contents and see that it is a share page and then download/display `/data`.

It could also contain machine readable metadata about the share...? e.g.

* Title
* Description
* Content type (display a video player if video etc.)
* "Main" - file path (and hash) of file considered to be the "entry point"
* One day, `index.html` can just use `window.ipfs` to read `.share-v0` to populate the download page content
* Share date
* File count?
* I'm just making this up...

`/data` - always a folder so that in the case of single files we can retain a file name

**Comment by olizilla** [comment]
More prior art
- live sharing example in js-ipfs https://github.com/ipfs/js-ipfs/pull/1343
- ipfs-senc https://github.com/jbenet/ipfs-senc
![screenshot 2018-06-25 09 27 09](https://user-images.githubusercontent.com/58871/41839019-fd887728-7859-11e8-9d8b-658ca243cd49.png)

**Comment by hacdias** [comment]
I've got a simple question I need to make sure. On WebUI we have a Share button. After clicking on it, we should get some link for a page like the ones on this issue, right? 

![image](https://user-images.githubusercontent.com/5447088/42078372-1a58f4b4-7b74-11e8-8e16-0edde0ed43b1.png)

**Comment by olizilla** [comment]
@hacdias yes. first pass would be this https://projects.invisionapp.com/d/main#/console/13924274/296567139/preview

**Comment by olizilla** [comment]
i don't think we want to hide the navbar though... if you can get a first pass working, we can review it.

**Comment by lidel** [comment]
Some additional UI examples on extension front:

- https://blog.mozilla.org/addons/2018/08/17/share-files-easily-with-extensions/

**Comment by lidel** [comment]
More prior art:

- https://dweb.page (just landed:  https://twitter.com/davidhawig/status/1065996471974199303)
  It requires a writable IPFS gateway and provides simple toggle for encrypting before upload:  
  > ![2018-11-23--18-45-40](https://user-images.githubusercontent.com/157609/48955838-0e3b7580-ef50-11e8-91dc-e9f020d1ef2b.png)

**Comment by lidel** [comment]
# [send.firefox.com](https://send.firefox.com/)

>  [Send](https://send.firefox.com/) uses end-to-end encryption to keep your data secure from the moment you share to the moment your file is opened. You can trust that your information is safe with Send. It also offers security controls that you can set. You can choose when your file link expires, the number of downloads, and whether to add an optional password for an extra layer of security. 
>
> [![](https://img.youtube.com/vi/eRHpEn2eHJA/maxresdefault.jpg)](https://www.youtube.com/watch?v=eRHpEn2eHJA)

**Comment by lidel** [comment]
# [instant.io](https://instant.io)

Sharing with WebTorrent https://github.com/webtorrent/instant.io

> ![2019-07-16--11-41-07](https://user-images.githubusercontent.com/157609/61284111-9eb81600-a7be-11e9-840b-030762a2ac7f.png)

**Comment by jessicaschilling** [comment]
Closing this as stale and prior art has evolved quite a bit in the interim -- also, we're hopefully doing some cleanup in https://github.com/ipfs-shipyard/ipfs-share-files in the near future. Please feel free to re-open if necessary.
