### ISSUE TITLE
How are we doing in 2018 Q3?

### ISSUE THREAD

**Issue by olizilla** [ipfs/ipfs-gui#63]
As per https://github.com/ipfs/pm/issues/668 let's check in!

- Do a score of your KRs on its current state (0 to 1 with regards to completion) - Mid-Q Actual Column
- Do a score of your KRs on what you believe the degree of completion by the end of the Quarter (0 to 1) - Mid-Q Projection Column
- Do a self-check on Priorities. See if the things you are working on are the most important ones, if they are not, explain to yourself why and check in if they are indeed more important that what is listed. If they happen to be more important, explain it to the team, if they are not, drop it in favour of the more important ones.
- List of things you are incredibly pumped about. It can be things you saw at the events, ideas that resulted from conversations, features that you are super excited about.
- Identify things that might take some of your time for the rest of your quarter (e.g. Holidays, Trainings, Confs, Weddings, etc)

Let's go through this on the next weekly sync, **Monday 20th Aug**

**Comment by alanshaw** [comment]
I've updated my scores on the spreadsheet.

**Priorities** - I've been pulled away from base32 CIDs by a js-ipfs release that had to happen before dweb summit. The week after dweb I prioritised the following:

* merging open PRs into js-ipfs (IPNS in particular before Vasco went on holiday)
* fixing with instances when IPFS badly validates inputs and ends up throwing instead of calling callback with error - towards my js-ipfs OKR of having the daemon run without crash for 10 days
* creating a discovery and transport module for IPFS that uses libdweb

I aim to spend the remainder of the quarter on base32 CIDs.

**Incredibly pumped about** - libdweb - after going to dweb summit and attending the workshop that gozala and soapdog ran and seeing what lidel had done with the protocol handler.

So, following dweb summit I've been spending some time implementing a MDNS discovery and TCP transport that uses **libdweb**:

* https://github.com/alanshaw/js-libp2p-webext-mdns
* https://github.com/alanshaw/js-libp2p-webext-tcp

These can be used with the embedded js-ipfs node that runs in IPFS companion to give it basically the same powers as js-ipfs running in Node.js. Obviously this includes local network discovery of JS or Go nodes but also p2p communication without websockets. This would be so AWESOME.

I think it's important that these libp2p modules exist for IPFS and I'm hoping 🤞 that IPFS (the organisation) using, testing and approving libdweb will make it a little more likely to be accepted into Firefox and then maybe adopted by Chrome and others.

**Things that might take some of your time** - I have a short vacation booked, and getting the 0.32 release out the door will take up a bunch of my time.

**Comment by olizilla** [comment]
Very nice write up @alanshaw. Some of that will fall under the feedback for in-web-browsers https://github.com/ipfs/in-web-browsers/issues/101 but the issues are linked now, so no need to move anything.

**Comment by fsdiogo** [comment]
I've updated the sheet with the status and projections of my KRs.

As to **priorities**, the main one is to ship the revamped WebUI, so my efforts have been pointed in that direction:

- Shipping the revamped peers page (https://github.com/ipfs-shipyard/ipfs-webui/pull/726)
- Shipping the ipfs share files app (https://github.com/ipfs-shipyard/ipfs-share-files)

This has been my focus and has put most of my KRs *on hold*. Once these are finished I'll tackle the KRs with the highest priorities.

**I'm pumped about**:

- Shipping the revamped WebUI 🌟 it's a significant upgrade from the current version and it will bring attention to the project from non tech-savy people. It can be a nice way to show some of the IPFS potential in a user friendly manner
- Shipping the IPFS Share Files, stand-alone app and integrated in the WebUI and Companion 🚀

**Comment by hacdias** [comment]
Hello! I already had updated the OKRs sheets so that's okay.

About the **priorities**, the main thing I'm focused on is the new WebUI. The Files page is almost 100% polished.

There's a KR to enable file encryption on WebUI, but I think that we should move that to the next quarter because as soon as this is shipped, Desktop will be my main focus. I'm already working a bit on it:

- https://github.com/ipfs-shipyard/ipfs-desktop/issues/652
- https://github.com/ipfs-shipyard/ipfs-desktop/pull/651

**Pumped about** the new WebUI and what we're going to do with IPFS Desktop. I'm improving its code a bit on the previously mentioned PR so it has a better error handling and better flow to start working on after WebUI is finished 😄

**Comment by olizilla** [comment]
**Priorities** I'm focused on webui / ipld explorer / the gui team / improving our process, and I think that's what we need. I got distracted by dweb summit, but it lead to https://explore.ipld.io _and_ https://proto.school/ getting on a boat, so it all worked out.

I haven't put enough time into hiring a user interface design hero. @meiqimichelle is leading the charge on that and I need get feeding back on https://github.com/protocol/design/issues/111

Once we get most of https://github.com/ipfs-shipyard/ipfs-webui/issues/749 ticked off, I'm going start setting up user feedback sessions, that we can use to define the priorities for webui v3!

I want to ship webui with enough time left this quarter to get feedback, and work with @hacdias on upgrading Desktop and @fsdiogo on creating the onboarding flows. I feel like there is a lot to do, but things are moving in the right direction and we're picking up momentum.

**I'm quite excited about (en-gb translation of _incredibly pumped_)** getting deep enough into IPLD that I can contribute to it's improvement.  A few months ago I wouldn't have been able determine if a given behaviour was a bug, but now I'm all like https://github.com/ipld/js-ipld-ethereum/issues/25 https://github.com/ipld/js-ipld-dag-pb/issues/84 
https://github.com/ipld/js-ipld-dag-pb/issues/79 https://github.com/ipld/ipld/issues/45

That and the conversations that came out of Berlin dev summit (let's visualise all the things, let's base32) and dweb (let's arewedistributedyet together). The positive feedback on IPLD Explorer means a lot too 💞 

**Things that might take some of your time** a long weekend adventure to https://www.emfcamp.org/ and there is possibility of having to research and prepare a session for mozfest, but it's not confirmed. Otherwise I'm all in on ipfs-gui.

**Comment by olizilla** [comment]
Q3 retrospective and Q4 planning is underway here https://github.com/ipfs/in-web-browsers/issues/110

**Comment by hacdias** [comment]
2018 Q3... closing this.
